name: Build with Unity and deploy to Github Pages

on:
  push:
    branches:
    - "master"

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
        matrix:
          targetPlatform:
            - WebGL
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Cache Library folders
        uses: actions/cache@v4.1.2
        with:
            path: Library
            key: Library-${{ matrix.targetPlatform }}
            restore-keys: Library-
      - name: Unity - Builder      
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload WebGL build to github-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/WebGL/WebGL

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      actions: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
